/*
<ul>
					<li>
						<div class="img-box">
							<a href="#">
								<img src="images/mix3.png" alt="">
							</a>
						</div>
						<a class="product-name" href="#">小米MIX3</a>
						<p class="product-price">3299元起</p>
						<span class="product-tag">新品</span>
					</li>
*/
//导航栏数据
var aShopItem = [
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},

	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX2',
			price:'3299',
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX2',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX2',
			price:'3299',
			tag:'新品'
		},

	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},

	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},

	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},

	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
		},

	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},

	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3',
			price:'3299',
			tag:'新品'
		},

	],
]
//左边内容数据
var aBannerContent = [
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米M'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米X3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MI3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小MIX3'		
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米8'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米8'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米8'		
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'小米MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'MIX3'		
		},
		{
			url:'http://www.baidu.com',
			img:'images/mix3.png',
			name:'MIX3'		
		}
	]
]