//顶部导航栏
var aNavItime = [
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
];

//分类
var aBoxis = [
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3'
		},
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1'
		},
	],
];
// 选项卡

var aCba = [
	[
		{
			url:'https://www.baidu.com/',
			b1:'减600元',
			img:'images/p1.jpg',
			name:'小米MIX 2 8GB+128GB 黑色',
			desc:'UNiboy 全陶瓷',
			price:'3699',
			view:{
				viewoo:'我不是来评价的我是来拉仇恨哈哈哈哈哈哈哈',
				viewpp:'清欢'
			},
		},
		{
			url:'https://www.baidu.com/',
			b1:'减600元',
			img:'images/p1.jpg',
			name:'小米MIX 2 8GB+128GB 黑色',
			desc:'UNiboy 全陶瓷',
			price:'3699',
			view:{
				viewoo:'我不是来评价的我是来拉仇恨哈哈哈哈哈哈哈',
				viewpp:'清欢'
			},
		},
		{
			top:{
				url:'https://www.baidu.com/',
				img:'images/ca.png',
				name:'小米净水器',
				jiaoge:'1899'

			},
			bottom:{
				url:'https://www.baidu.com/',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
];