var aNavItime = [
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
	[
		{
			url:'https://www.baidu.com/',
			img:'images/p2.jpg',
			name:'小米MIX1',
			jiage:'3299',
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX2',
			jiage:'3299',
			tag:'新品'
		},
		{
			url:'https://www.baidu.com/',
			img:'images/p1.jpg',
			name:'小米MIX3',
			jiage:'3299',
			tag:'新品'
		}
	],
]

